packages:
  - '.'

catalog:
  '@astrojs/check': '^0.9.8'
  '@astrojs/mdx': '^4.3.14'
  '@astrojs/rss': '^4.0.18'
  '@astrojs/sitemap': '^3.7.2'
  '@astrojs/tailwind': '^6.0.2'
  '@notionhq/client': '^2.2.14'
  astro: '^5.9.4'
  tailwindcss: '^3.4.1'
  typescript: '^5.3.3'
