packages:
  - "."

catalog:
  "@astrojs/check": "^0.9.8"
  "@astrojs/mdx": "^5.0.4"
  "@astrojs/rss": "^4.0.18"
  "@astrojs/sitemap": "^3.7.2"
  "@tailwindcss/vite": "^4.0.0"
  "@notionhq/client": "^2.2.14"
  astro: "^6.1.9"
  tailwindcss: "^4.0.0"
  typescript: "^5.3.3"
